---
driver:
  name: vagrant

provisioner:
  name: ansible_playbook
  ansible_version: 2.8.5
  ansible_yum_repo: "https://dl.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-5.noarch.rpm"
  hosts: all
  require_chef_for_busser: false
  require_ruby_for_busser: false
  ansible_verbose: false
  ansible_verbosity: 3
  ansible_check: false
  ansible_diff: true
  ansport:
  max_ssh_sessions: 6

verifier:
  ruby_bindir: /opt/chef/embedded/bin

platforms:
  - name: ansible-ubuntu-18.0.4-x86_64
    driver_config:
      box: ansible-ubuntu-18.0.4-x86_64
      box_url: file:///Users/lindsworthgarvey/vagrantRepo/ansible-ubuntu-18.0.4-x86_64
      synced_folders:
        - [ "~/symbridgeRepo/ansiblePlaybook", "/ansiblePlaybook"]
        - [ "~/Downloads/Software", "/instImages"]

suites:
  - name: gitlab-ci
    driver:
      vm_hostname: symtstgtlbcivm001.symbridge.com
      customize:
        cpus: 2
        memory: 2048
        natdnshostresolver1: 'on'
      network:
        - ["private_network", {ip: "10.13.3.5"}]
        - ["forwarded_port", {guest: 80, host: 8080}]
        - ["forwarded_port", {guest: 443, host: 8443}]
        - ["forwarded_port", {guest: 9090, host: 9090}]
    provisioner:
      hosts: symtstgtlbcivm001
      require_ansible_repo: true
      playbook: gitlabci.yml
      ansible_vault_password_file: [".kitchenCIvault", ".symtstGTLBCIvault"]

  - name: gitlab-runner-01
    driver:
      vm_hostname: symtstgtlbrnvm001.symbridge.com
      customize:
        cpus: 1
        memory: 1024
        natdnshostresolver1: 'on'
      network:
        - ["private_network", {ip: "10.13.3.6"}]
    provisioner:
      hosts: symtstgtlbrnvm001.symbridge.com
      require_ansible_repo: true
      playbook: gitlabrunner.yml
      ansible_vault_password_file: [".kitchenCIvault", ".symtstGTLBCIvault" ]

  - name: gitlab-runner-02
    driver:
      vm_hostname: symtstgtlbrnvm002.symbridge.com
      customize:
        cpus: 1
        memory: 1024
        natdnshostresolver1: 'on'
      network:
        - ["private_network", {ip: "10.13.3.7"}]
    provisioner:
      hosts: symtstgtlbrnv002.symbridge.com
      require_ansible_repo: true
      playbook: gitlabrunner.yml
      ansible_vault_password_file: [".kitchenCIvault", ".symtstGTLBCIvault"]
# ...
