---
- name: Add mappings to /etc/hosts
  blockinfile:
    path: /etc/hosts
    block: |
      {{ item.ip }} {{ item.fqdn }} {{ item.name }}
    marker: "#{ mark } ANSIBLE MANAGED BLOCK {{ item.name }}"
  with_items:
    - { ip: 10.13.3.5, fqdn: symtstgtlbcivm001.symbridge.com, name: symtstgtlbcivm001 }
    - { ip: 10.13.3.6, fqdn: symtstgtlbrnvm001.symbridge.com, name: symtstgtlbrnvm001 }
    - { ip: 10.13.3.7, fqdn: symtstgtlbrnvm002.symbridge.com, name: symtstgtlbrnvm002 }
  when:  ansible_hostname is search('symtstgtlb')

...
