---
- name: Add mappings to /etc/hosts
  blockinfile:
    path: /etc/hosts
    block: |
      {{ item.ip }} {{ item.fqdn }} {{ item.name }}
    marker: "#{ mark } ANSIBLE MANAGED BLOCK {{ item.name }}"
  with_items:
    - { ip: 10.13.3.5, fqdn: usctvltstgitlbci01v.curbstone.com, name: usctvltstgitlbci01v }
    - { ip: 10.13.3.6, fqdn: usctvltstgitlbrn01v.curbstone.com, name: usctvltstgitlbrn01v }
    - { ip: 10.13.3.7, fqdn: usctvltstgitlbrn02v.curbstone.com, name: usctvltstgitlbrn02v }
  when:  ansible_hostname is search('usctvltstgitlb')

...
