---
#
# Install supporting packages
#

- name: Install common packages with yum
  yum:
    name:
      - bc
      - git
      - unzip
      - bsdtar
      - sysstat
      - iptraf
      - yum-utils
      - epel-release
      - logrotate
      - postfix
      - openssh-server
      - http://rpms.remirepo.net/enterprise/remi-release-7.rpm
    state: present

- name: Get NodeJS Repo Script
  get_url:
    url: https://rpm.nodesource.com/setup_10.x
    dest: /tmp/setup_10.x
    mode: 0755

- name: Setup NodeJS Repository
  shell: /tmp/setup_10.x
  ignore_errors: yes
  args:
    warn: yes

- name: Install NodeJS
  yum:
    name:
      - nodejs
    state: present

- name: Get GitLab Repo
  get_url:
    url: https://packages.gitlab.com/install/repositories/gitlab/gitlab-ce/script.rpm.sh
    dest: /tmp/script.rpm.sh
    mode: 0755

- name: Get GitLab Runner Repo
  get_url:
    url: https://gitlab-runner-downloads.s3.amazonaws.com/latest/rpm/gitlab-runner_amd64.rpm
    dest: /tmp/gitlab-runner_amd64.rpm
    mode: 0755

- name: Setup GitLab Repository
  shell: /tmp/script.rpm.sh
  ignore_errors: yes
  args:
    warn: yes

...
