---
- name: Configure test-kitchen Firewalld Port {{ item }}
  firewalld:
    port: "{{ item }}"
    immediate: yes
    permanent: true
    state: enabled
    zone: public
  with_items:
    - "80/tcp"
    - "443/tcp"
    - "9090/tcp"
    - "6379/tcp"
  when: ansible_fqdn is search('usctvltstgitlbci01v') and ansible_os_family == 'RedHat'
  tags: firewalld

- name: Configure Debian Firwalld Ports
  block:
    - name: Allow New,Related and Established connections to GitLab
      iptables:
        chain: INPUT
        protocol: tcp
        destination_port: "{{ item }}"
        ctstate: NEW,ESTABLISHED,RELATED
        jump: ACCEPT
        state: present
      become: yes
      with_items:
        - "80"
        - "443"
        - "9090"
        - "6379"
      when: ansible_hostname is search('usctvltstgitlbci01v') and ansible_os_family == 'Debian'
