---
#
# Install supporting packages
#

- name: Install Redis
  yum:
    name:
      - redis
      - policycoreutils
    state: present
    enablerepo: remi

- name: Enable Redis Service
  service:
    name: "{{ item }}"
    enabled: yes
    state: started
  with_items:
    - [ 'redis','postfix' ]
  tags: redisService

- name: Install GitLab-CE
  yum:
    name:
      - gitlab-ce
      - "{{ stagingDir }}/gitlab-runner_amd64.rpm"
    state: present
    enablerepo: gitlab_gitlab-ce

# - name: Create GitLab Dir
#   file:
#     path: "/etc/gitlab"
#     state: directory
#     owner: root
#     group: root
#     mode: 0755
#
# - name: Render gitlab-ce template
#   template:
#     src: gitlab.rb.j2
#     dest: "{{ stagingDir }}/gitlab/gitlab.rb"
#     owner: root
#     group: root
#     mode: 0600

#===============================================================================
#
# TODO:
#    Search for Regex before attempting to replace it for idempotency
#

- name: Set Gitlab EXTERNAL_URL
  lineinfile:
    path: /etc/gitlab/gitlab.rb
    regexp: "^external_url 'http://gitlab.example.com'"
    line: external_url 'http://{{ ansible_fqdn }}'

#===============================================================================

- debug:
    msg: "GITLAB_ROOT_PASSWORD: {{ GitLab_Passwd }}"

- name: Configure gitlab-ce
  shell: gitlab-ctl reconfigure
  ignore_errors: true
  args:
    warn: true
  environment:
    EXTERNAL_URL: "https://{{ ansible_fqdn }}"
    GITLAB_ROOT_PASSWORD: "{{ GitLab_Passwd }}"

  notify: "{{ item }}"
  with_items:
    - service restart redis
    - service restart postfix
    - service restart firewalld
...
