---
#
# Install supporting packages
#

- name: Install Redis
  yum:
    name:
      - redis
      - policycoreutils
    state: present
    enablerepo: remi

- name: Enable Redis Service
  service:
    name: "{{ item }}"
    enabled: yes
    state: started
  with_items:
    - [ 'redis','postfix' ]
  tags: redisService

- name: Install GitLab-CE
  yum:
    name:
      - gitlab-ce
      - "{{ tmpDir }}/gitlab-runner_amd64.rpm"
    state: present
    enablerepo: gitlab_gitlab-ce

- name: Set Gitlab EXTERNAL_URL
  lineinfile:
    path: /etc/gitlab/gitlab.rb
    regexp: "^external_url 'http://gitlab.example.com'"
    line: external_url 'http://{{ ansible_fqdn }}'

- debug:
    msg: "GITLAB_ROOT_PASSWORD: {{ GitLab_Passwd }}"

- name: Configure gitlab-ce
  shell: gitlab-ctl reconfigure
  ignore_errors: true
  args:
    warn: true
  environment:
    EXTERNAL_URL: "https://{{ ansible_fqdn }}"
    GITLAB_ROOT_PASSWORD: "{{ GitLab_Passwd }}"

- debug:
    msg: "GITLAB_ROOT_PASSWORD: {{ GitLab_Passwd }}"

  notify: "{{ item }}"
  with_items:
    - service restart redis
    - service restart postfix
    - service restart firewalld
...
