---
#
# Install supporting packages
#

- name: Get Helm Binary
  get_url:
    url: https://get.helm.sh/helm-v3.3.4-linux-amd64.tar.gz
    dest: "{{ tmpDir }}/helm-v3.3.4-linux-amd64.tar.gz"
    checksum: 'sha256:b664632683c36446deeb85c406871590d879491e3de18978b426769e43a1e82c'
    mode: 0755


...
