---
#
# Install supporting packages
#

- name: Check if GitLab-ctl file exists.
  stat:
    path: /usr/bin/gitlab-ctl
  register: gitlab_ctl

- name: Check if GitLab Config file exists.
  stat:
    path: /etc/gitlab/gitlab.rb
  register: gitlab_config_file

- name: Install Debian GitLab Packages
  block:
    - name: Install Redis
      yum:
        name:
          - redis
          - policycoreutils
        state: present
        enablerepo: remi
      when: ansible_os_family == 'RedHat'

    - name: Enable Redis Service
      service:
        name: "{{ item }}"
        enabled: yes
        state: started
      with_items:
        - [ 'redis','postfix' ]
      when: ansible_os_family == 'RedHat'
      tags: redisService

    - name: Setup GitLab Repository
      shell: "{{ stagingDir }}/script.rpm.sh"
      ignore_errors: yes
      args:
        warn: yes

    - name: Install GitLab-EE Runner
      yum:
        name:
          - gitlab-ee
          - "{{ stagingDir }}/gitlab-runner_amd64.rpm"
        state: present
        enablerepo: gitlab_gitlab-ee
      when: "ansible_fqdn is search('symtstgtlbcivm001') and not gitlab_ctl.stat.exists"

  when: ansible_os_family == 'RedHat'

- name: Install Debian GitLab Packages
  block:
    - name: Install Debian GitLab-EE Packages
      apt:
        pkg:
          - gitlab-ee={{ gitlabEE.ciVersion }}
        state: present
        update_cache: yes
        dpkg_options: force-confdef,force-confold
      when: not gitlab_ctl.stat.exists

      notify: "{{ item }}"
      with_items:
        - service restart ufw

  when: ansible_os_family == 'Debian'

- name: Configure gitlab-runner sudoers config
  copy:
    src: sudoers.d_gitlab-runner
    dest: /etc/sudoers.d/gitlab-runner
    owner: root
    group: root
    mode: 0400

- name: Create GitLab Dir
  file:
    dest: "{{ item.dst  }}"
    state: directory
    owner: root
    group: root
    mode: "{{ item.mode }}"
  with_items:
      - { dst: /etc/gitlab, mode: '0775' }
      - { dst: /etc/gitlab/ssl, mode: '0755' }
#
# TODO:
#   Add task for configuring TLS
#

- name: Render gitlab-ee template
  template:
    src: gitlab.rb.j2
    dest: "{{ gitlabDir }}/gitlab.rb"
    owner: root
    group: root
    mode: 0600

- name: Configure gitlab-ee
  shell: gitlab-ctl reconfigure
  ignore_errors: true
  args:
    warn: true
  environment:
    EXTERNAL_URL: "{{ gitlabciUrl }}"
    GITLAB_ROOT_PASSWORD: "{{ initial_root_password }}"
  tags: ['configGitlabCe']
...
