---
  #
  # Import tasks
  #
- import_tasks: "{{ role_path }}/../assert-env.yml"
  tags: ['assertEnv']

- import_tasks: configure-firewalld.yml
  tags: ['configHost']

- import_tasks: configure-pkg-repos.yml
  tags: ['configHost']

- import_tasks: install-packages.yml
  tags: ['installPackages']

- name: Import Common role
  import_role:
    name: common
  tags: ['configCommonDeps', 'installCommonDeps']

- debug:
    msg: "GITLAB_ROOT_PASSWORD: {{ GitLab_Passwd }}"
  when: env is search('tst')
