---
  #
  # Import tasks
  #
- import_tasks: "{{ role_path }}/../assert-env.yml"
  tags: ['assertEnv']

- import_tasks: configure-firewalld.yml
  tags: ['configHost']

- import_tasks: configure-gitlab-pkgs-repos.yml
  tags: ['configHost']

- import_tasks: install-gitlab-pkgs.yml
  tags: ['installPackages']

- debug:
    msg: "GITLAB_ROOT_PASSWORD: {{ initial_root_password }}"
  when: env is search('tst')
