---
docker:
  version: 19.03.13
  compose: 1.27.4

- name: Get GitLab Repo
  get_url:
    url: https://github.com/docker/compose/releases/download/{{ docker.compose }}/docker-compose-Linux-x86_64
    dest: "{{ localBin }}/sdocker-compose"
    mode: 0755
