---
- hosts: localhost

  vars:
    gitLab_email:
      smtp_server: smtp.curbstone.com
      smtp_port: 25

    gitlabciUrl: "{{ 'https://usctvltstgitlbci01v.curbstone.com' if env is search('tst')
                    else 'https://usctvlprdgitlbci01v.curbstone.com'
                    }}"

    registration_token: "{{ 'uvu1zFo5okhrn69uBLApq' if env is search('tst')
                        else  gitlabAccessToken
                       }}"
    gitlabRegistry:
      backup_path: '/var/opt/gitlab/backups'
      Url: "{{ gitlabciUrl }}"
      UrlPort: '5050'


  tasks:

    - name: set_fact for localhost
      tags: always
      set_fact:
        env: "{{ ansible_hostname.split('usctvl')[1] }}"
        local_env: "{{ ansible_hostname.split('usctvl(tst|dev|uat|prd)') }}"
      when: ansible_hostname is search('usctvl(tst|dev|uat|prd)')

    - debug:
        msg: "Host environment is : {{ env }} HostName is {{ local_env }}"

    - assert:
        that:
          - env is search('tst|dev|uat|prd')

    - debug:
        msg: "{{ gitlabRegistry.Url }} ==> {{ gitlabRegistry.UrlPort }}"
