---

- name: service restart redis
  service:
    name: redis
    state: restarted

- name: service restart postfix
  service:
    name: postfix
    state: restarted

- name: service restart firewalld
  service:
    name: firewalld
    state: restarted
