---
- name: Create Staging Dir
  file:
    path: "{{ stagingDir }}"
    state: directory
    owner: root
    group: root
    mode: 0755
    
- name: Install Common Debian Gitlab-CI Packages
  block:
    - name: Install common packages with apt
      apt:
        pkg:
          - bc
          - git
          - wget
          - gzip
          - curl
          - unzip
          - sysstat
          - iptraf
          - rsyslog
          - postfix
          - logrotate
          - openssh-server
        state: present
        update_cache: yes
        dpkg_options: force-confdef,force-confold

    # - name: Install common Docker for Ubuntu
    #   apt:
    #     pkg:
    #       - gnupg-agent
    #       - ca-certificates
    #       - apt-transport-https
    #       - software-properties-common
    #     state: present
    #     update_cache: yes
    #     dpkg_options: force-confdef,force-confold
    #
    # - name: Add Docker GPG key
    #   apt_key:
    #     url: https://download.docker.com/linux/ubuntu/gpg
    #     id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    #     state: present
    #
    # - name: Add Docker Repo
    #   apt_repository:
    #     repo: deb https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable
    #     state: present
    #     update_cache: yes
    #
    # - name: Install docker
    #   apt:
    #     pkg:
    #       - docker-ce
    #       - docker-ce-cli
    #       - containerd.io
    #     update_cache: yes
    #     dpkg_options: force-confdef,force-confold
  when: ansible_os_family == 'Debian'


- name: Install Common Debian Gitlab-CI Packages
  block:
    - name: Install common RedHat packages
      yum:
        pkg:
          - bc
          - git
          - wget
          - gzip
          - curl
          - unzip
          - sysstat
          - iptraf
          - logrotate
          - postfix
          - openssh-server
        state: present

    - name: Download Infra Code Packages
      get_url:
        url: "{{ item.url }}"
        dest: "{{ item.dest }}"
        mode: " {{ item.mode }}"
      with_items:
        - { url: 'https://github.com/gruntwork-io/terragrunt/releases/download/v0.25.5/terragrunt_linux_amd64', dest: '{{ localBin }}/terragrunt', mode: '0755' }
        - { url: 'https://releases.hashicorp.com/terraform/0.13.5/terraform_0.13.5_linux_amd64.zip', dest: '{{ stagingDir }}', mode: '0755' }
        - { url: 'https://get.helm.sh/helm-v3.3.4-linux-amd64.tar.gz', dest: '{{ stagingDir }}', mode: '0755' }
      tags: ['installInfraCodePackages']

    - name: "Unarchive {{ item }}"
      unarchive:
        src: "{{ item }}"
        dest: "{{ localBin }}"
        mode: 0755
      loop:
        - "{{ stagingDir }}/terraform_0.13.5_linux_amd64.zip"
        - "{{ stagingDir }}/helm-v3.3.4-linux-amd64.tar.gz"

    - name: Recursively Remove stagingDir
      file:
        path: "{{ stagingDir}}"
        state: absent
  when: ansible_os_family == 'RedHat'
