---
#
# Install supporting packages
#
- name: Create GitLab Dir
  file:
    dest: "{{ item.dst  }}"
    state: directory
    owner: root
    group: root
    mode: "{{ item.mode }}"
  with_items:
      - { dst: /etc/gitlab, mode: '0775' }
      - { dst: /etc/gitlab/ssl, mode: '0755' }

- name: Copy GitLab SSL Certs
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dst }}"
    owner: root
    group: root
    mode: 0400
  with_items:
    - { src: vault/ca.crt, dst: /etc/gitlab/ssl/ca.crt }
    - { src: vault/server.crt, dst: "/etc/gitlab/ssl/{{ ansible_fqdn }}.crt" }
    - { src: vault/server.key, dst: '/etc/gitlab/ssl/{{ ansible_fqdn }}.key' }

...
