---
  #
  # Import tasks
  #
- import_tasks: "{{ role_path }}/../config_local_hosts.yml"
  tags: ['configLocalHost', 'configEtcHosts']

- import_tasks: "{{ role_path }}/../assert-env.yml"
  tags: ['assertEnv']

- name: Import docker role
  import_role:
    name: docker
  tags: ['configDocker', 'installDocker']

- import_tasks: install-certs.yml
  when: ansible_fqdn is search('usctvltstgitlbci')
  tags: ['installCerts']

- import_tasks: configure-runner.yml
  when: env is search('tst')
  tags: ['configRunnerHost']
