---
  #
  # Import tasks
  #
- import_tasks: "{{ role_path }}/../config_local_hosts.yml"
  tags: ['configLocalHost', 'configEtcHosts']

- import_tasks: "{{ role_path }}/../assert-env.yml"
  tags: ['assertEnv']

- import_tasks: install-common-pkgs.yml
  tags: ['installCommonPkgs']
