---
- name: Configure test-kitchen Firewalld Port {{ item }}
  firewalld:
    port: "{{ item }}"
    immediate: yes
    permanent: true
    state: enabled
    zone: public
  with_items:
    - "80/tcp"
    - "443/tcp"
    - "9090/tcp"
    - "6379/tcp"
  tags: firewalld

#
# Install supporting runner packages
#

- name: Install common packages with yum
  yum:
    name:
      - bc
      - git
      - unzip
      - bsdtar
      - sysstat
      - iptraf
      - yum-utils
      - epel-release
      - logrotate
      - postfix
      - openssh-server
      - http://rpms.remirepo.net/enterprise/remi-release-7.rpm
    state: present

- name: Get NodeJS Repo Script
  get_url:
    url: https://rpm.nodesource.com/setup_10.x
    dest: "{{ stagingDir }}/setup_10.x"
    mode: 0755

- name: Setup NodeJS Repository
  shell: "{{ stagingDir }}/setup_10.x"
  ignore_errors: yes
  args:
    warn: yes

- name: Install NodeJS
  yum:
    name:
      - nodejs
    state: present

- name: Get GitLab Runner Repo
  get_url:
    url: https://gitlab-runner-downloads.s3.amazonaws.com/latest/rpm/gitlab-runner_amd64.rpm
    dest: "{{ stagingDir }}/gitlab-runner_amd64.rpm"
    mode: 0755
