---
#
# Install supporting packages
#

- name: Install GitLab
  yum:
    name:
      - "{{ stagingDir }}/gitlab-runner_amd64.rpm"
    state: present
  register: installGitLabRunner

- name: Generate GitLab-Runner ssh-keys
  shell: ssh-keygen -t rsa -N "" -b 2048 -f ~/.ssh/id_rsa -C gitlab-runner@{{ ansible_fqdn }}
  ignore_errors: true
  args:
    warn: true

- name: Get Helm Binary
  get_url:
    url: https://get.helm.sh/helm-v3.3.4-linux-amd64.tar.gz
    dest: "{{ stagingDir }}/helm-v3.3.4-linux-amd64.tar.gz"
    checksum: 'sha256:b664632683c36446deeb85c406871590d879491e3de18978b426769e43a1e82c'
    mode: 0755

  notify: "{{ item }}"
  with_items:
    - service restart firewalld

...


#===============================================================================
#
# TODO
#   Register Runners https://docs.gitlab.com/runner/register/
#
#===============================================================================

# - name: Render gitlab-runner Register config
#   template:
#     src: config.toml.j2
#     dest: /etc/gitlab-runner/config.toml
#     owner: gitlab-runner
#     group: gitlab-runner
#     mode: 0644
#===============================================================================
