---
#
# Install supporting runner packages
#
- name: Create Staging Dir
  file:
    path: "{{ stagingDir }}"
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Configure Debian Gitlab-CI Requirements
  block:
    - name: Install common packages with yum
      yum:
        name:
          - yum-utils
          - epel-release
          - logrotate
          - postfix
          - openssh-server
          - http://rpms.remirepo.net/enterprise/remi-release-7.rpm
        state: present

    - name: Get NodeJS Repo Script
      get_url:
        url: https://rpm.nodesource.com/setup_10.x
        dest: "{{ stagingDir }}/setup_10.x"
        mode: 0755

    - name: Setup NodeJS Repository
      shell: "{{ stagingDir }}/setup_10.x"
      ignore_errors: yes
      args:
        warn: yes

    - name: Install NodeJS
      yum:
        name:
          - nodejs
        state: present

    - name: Get GitLab Runner Repo
      get_url:
        url: https://gitlab-runner-downloads.s3.amazonaws.com/latest/rpm/gitlab-runner_amd64.rpm
        dest: "{{ stagingDir }}/gitlab-runner_amd64.rpm"
        mode: 0755

    - name: Install GitLab Runner
      yum:
        name:
          - "{{ stagingDir }}/gitlab-runner_amd64.rpm"
        state: present
      register: installGitLabRunner

      notify: "{{ item }}"
      with_items:
        - service restart firewalld
  when: ansible_os_family == 'RedHat'

- name: Configure Debian Gitlab-CI Requirements
  block:

    - name: Install NodeJS
      apt:
        pkg:
          - nodejs
        autoremove: yes
        state: present

    - name: Get Debian GitLab Runner Repo
      get_url:
        url: https://packages.gitlab.com/install/repositories/runner/gitlab-runner/script.deb.sh
        dest: "{{ stagingDir }}/script.gitlab-runner.deb.sh"
        mode: 0755

    - name: Setup Debian GitLab-EE Repository
      shell: "{{ stagingDir }}/script.gitlab-runner.deb.sh"
      ignore_errors: yes
      args:
        warn: yes

    - name: Install Debian GitLab-runner
      apt:
        pkg:
          - gitlab-runner={{ gitlabEE.runnerVersion }}
        update_cache: yes

      notify: "{{ item }}"
      with_items:
        - service restart ufw

  when: ansible_os_family == 'Debian'
