---
  #
  # Import tasks
  #
- import_tasks: "{{ role_path }}/../assert-env.yml"
  tags: ['assertEnv']

- import_tasks: configure-firewalld.yml
  tags: ['configHostFw']

- import_tasks: install-runner-pkgs.yml
  tags: ['installRunnerPackages']

- import_tasks: setup-gitlab-runner.yml
  tags: ['installRunnerPackages']
...
