---
  #
  # Import tasks
  #

- name: Import docker role
  import_role:
    name: docker
  tags: ['configDocker', 'installDocker']

- import_tasks: configure-firewalld.yml
  tags: ['configHostFw']

- import_tasks: install-runner-pkgs.yml
  tags: ['installRunnerPackages']

# - import_tasks: configure-runner.yml
#   tags: ['configRunnerHost']
