---
- name: Configure gitlab-runner sudoers config
  copy:
    src: sudoers.d_gitlab-runner
    dest: /etc/sudoers.d/gitlab-runner
    owner: root
    group: root
    mode: 0400

- name: Create GitLab-Runner Dir
  file:
    dest: "{{ item.dst  }}"
    state: directory
    owner: gitlab-runner
    group: gitlab-runner
    mode: "{{ item.mode }}"
  with_items:
    - { dst: /etc/gitlab-runner, mode: '0755' }
    - { dst: /etc/gitlab-runner/certs, mode: '0755' }

#
# TODO
#   Configure TLS for runner
#

- name: Register gitlab-runner
  shell: |
     gitlab-runner register \
         --tag-list shell  \
         -n -r "{{ registration_token }}"  \
         --url "{{ gitlabciUrl }}" \
         --run-untagged=true  \
         --locked=false  \
         --name="{{ ansible_fqdn }}" \
         --executor=shell
  ignore_errors: false
  args:
    warn: false
  register: registerGitLabRunner

- name: Set prepare .gitConfig
  shell: |
    git config --global http.sslCAPath /etc/gitlab-runner/certs/
  become: yes
  become_user: gitlab-runner
  ignore_errors: true
  args:
    warn: true

- name: Create GitLab-Runner .ssh Dir
  file:
    dest: "{{ item.dst  }}"
    state: directory
    owner: gitlab-runner
    group: gitlab-runner
    mode: "{{ item.mode }}"
  with_items:
      - { dst: /home/gitlab-runner/.ssh, mode: '0700' }

- name: Copy GitLab-Runner SSH Keys
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dst }}"
    owner: gitlab-runner
    group: gitlab-runner
    mode: 0700
  no_log: true
  with_items:
    - { src: kitchenCIgitlabrunner/symtstgtlb-id_rsa, dst: /home/gitlab-runner/.ssh/id_rsa }
    - { src: kitchenCIgitlabrunner/symtstgtlb-id_rsa.pub, dst: /home/gitlab-runner/.ssh/id_rsa.pub }
  when: ansible_fqdn is search('symtstgtlb')

- name: Configure gitlab-runner Authorized Keys
  authorized_key:
    user: gitlab-runner
    key: "{{ item }}"
    state: present
    validate_certs: False
    manage_dir: True
  no_log: true
  with_file:
    - kitchenCIgitlabrunner/symtstgtlb-id_rsa.pub
  when: ansible_fqdn is search('symtstgtlb')

- name: Render gitlab-runner ssh_config
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dst }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: 0600
  no_log: true
  with_items:
    - { src: runner_ssh_config.j2, dst: /home/gitlab-runner/.ssh/ssh_config, owner: 'gitlab-runner', group: 'gitlab-runner' }

...
