galaxy_info:
  author: Len Garvey <len.garvey@marcusalexandra.com>
  company: Marcus-Alexandra, LLC

  license: Proprietary

  min_ansible_version: 2.8

  platforms:
  - name: EL
    versions:
    - 7
